# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '>=14.15.3'
          
      - name: install deps
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
          
      - name: build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
          
      - name: test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
          
      - name: GitHub Branch Deploy
        uses: zekth/gh-deploy-action@1.0.0
        with:
          build_dir: dist
          # Personnal access token
          gh_token: ${{ secrets.TOKEN }}
          # Branch targeted for the deployment
          target_branch: production
          
      
